### ISSUE TITLE
Holy Moly

### ISSUE THREAD

**Issue by tomjn** [stuttter/wp-spider-cache#1]
https://github.com/stuttter/wp-spider-cache/blob/master/includes/class-output-cache.php#L396

```
    protected function do_variants( $dimensions = false ) {
        // This function is called without arguments early in the page load,
        // then with arguments during the OB handler.
        if ( false === $dimensions ) {
            $dimensions = wp_cache_get( "{$this->url_key}_vary", $this->group );
        } else {
            wp_cache_set( "{$this->url_key}_vary", $dimensions, $this->group, $this->max_age + 10 );
        }
        // Sort keys
        if ( is_array( $dimensions ) ) {
            ksort( $dimensions ); // OCD much?
            foreach ( $dimensions as $key => $function ) {
                $fun   = create_function( '', $function );
                $value = $fun();
                $this->keys[ $key ] = $value;
            }
        }
    }
```

**Comment by JJJ** [comment]
Yeah; `create_function()` is terrible. I wonder if I can get away with callbacks here instead.

**Comment by skeltoac** [comment]
I remember developing this logic for batcache. It is necessary to serialize the function so it can be stored in the object cache. I didn't find a better way to serialize a callback.

**Comment by tomjn** [comment]
Is that so that due to the earliness of the callbacks?

**Comment by skeltoac** [comment]
Correct. The purpose is to serve variants from the cache without loading any plugin or theme code.

**Comment by JJJ** [comment]
> I remember developing this logic for bat cache

I hope it's obvious when I say "terrible" I mean it with the utmost respect and admiration. <3

> Is that so that due to the earliness of the callbacks?

Partly, yes. A filter hook would be an interesting solution (similar to `map_meta_cap`) to let plugins stack variants on top of one another, but as the docs say:

```
Variants can be set by functions which use early-set globals like $_SERVER to
run simple tests. Functions defined in WordPress, plugins, and themes are not
available and MUST NOT be used.
```

The old `vary_cache_on_function()` function (which I renamed to `wp_output_cache_vary()` because I could) does some rudimentary checking to prevent the nastier known possibilities. 

I think the best alternative is to drop PHP 5.2 and lower, and use anonymous functions. I do not know of any combination of the `call_user_func()` and `is_callable()` function families that would allow for the same flexibility in PHP 5.2 and lower.

**Comment by tomjn** [comment]
I'm inclined that 5.2 should be dropped for at least 5.3 ( preferably 5.4/5.5 ), but how would anonymous functions be much better? The problem still remains that they need to be packaged up somehow and stored

**Comment by skeltoac** [comment]
Check out the docs for `vary_cache_on_function()`, which is renamed to `wp_output_cache_vary()` here. This is probably the most advanced or hard to grasp feature in batcache.
https://vip.wordpress.com/documentation/caching/batcache/vary_cache_on_function/

**Comment by JJJ** [comment]
> how would anonymous functions be much better

`create_function()` still uses `eval()` internally, and has a bad reputation for not being very performant.

Anonymous functions are more performant, and the closure syntax is (I think) easier on the eyes.

**Comment by skeltoac** [comment]
> `create_function()` still uses `eval()` internally, and has a bad reputation for not being very performant.

Implying that `create_function()` should be avoided due to risk of arbitrary code execution? `eval()` is risky only when you pass it unsafe code. Hard-coded strings can be perfectly safe. Strings built from variables can also be safe if the inputs are controlled. Safety is in the hands of the person writing the string. Give them documentation and then trust them with their own safety.

On WordPress.com there are dozens of calls to `vary_cache_on_function()`, mostly in VIP theme code so it's being successfully used by many different devs. Typical calls are brief and obviously safe, like this:

```
vary_cache_on_function('return (bool) preg_match("/iPhone|iPad|iPod/i", $_SERVER["HTTP_USER_AGENT"]);');
```

As for performance, I look forward to your experiments in eliminating `create_function()`.

**Comment by JJJ** [comment]
> Implying that create_function() should be avoided due to risk of arbitrary code execution? 

That's not fair. I'm not being coy or making things up; `eval()` is largely avoided everywhere. WordPress  actively removed usages years ago, and continues to avoid introducing new ones -- naturally plugins will largely follow suit.

https://core.trac.wordpress.org/search?q=eval%28%29&noquickjump=1&changeset=on&ticket=on

> eval() is risky only when you pass it unsafe code (...)

Everything is risky when you pass it unsafe code. Heck, it's risky with safe code, too.

I believe we (developers) have an obligation to try our best to write code that solves more problems than it introduces, and in most cases comes with convenient to use APIs for other developers to tap into. I think `eval()` is probably the simplest & most powerful option, but I don't think it's the most convenient or safe. I'm okay being wrong, though!

Either way, I'm fine with how it works today, and I'm happy we have this issue here to think about alternatives together. <3

**Comment by skeltoac** [comment]
Gloves off! ;-) <3<3<3

> > Implying that `create_function()` should be avoided due to risk of arbitrary code execution?
> 
> That's not fair. I'm not being coy

It was a fair question. @Tarendai posted an issue called "Holy Moly" containing only a block of code. (Who invited Linus? :wink:) That's where the implying began. @johnjamesjacoby commented "`create_function()` is terrible" but still left the problem unsaid. Security issue? Performance issue? Coding style issue? Not said.

> `create_function()` still uses `eval()` internally, and has a bad reputation for not being very performant.

That's the first mention of `eval()` but the only problem given is a bad reputation, performance-wise. Then more talk of performance. So much for not being coy.

I knew on sight that this was about the `eval()` taboo and that the implication was arbitrary code execution vulnerability. I asked the "implying" question because you were still talking about performance as if it mattered when this question of vulnerability was still in the air. Let's answer the vulnerability question and then consider whether performance is an issue.

The `eval()` taboo is really just a taboo everyone has to get over so they can think rationally about `eval()` again. The WordPress community has amplified this unthinking prohibition so militantly that it causes otherwise good developers to post terrible github issues without even attempting to understand how or why a working and successful system was built using `create_function()`.

Is `eval()` itself a vulnerability? No. It is _not_ risky with safe code. It is not deprecated or even relegated to an extension to keep it out of the reach of PHP users. This is what php.net says:

> _Caution_ The eval() language construct is very dangerous because it allows execution of arbitrary PHP code. Its use thus is discouraged. If you have carefully verified that there is no other option than to use this construct, pay special attention not to pass any user provided data into it without properly validating it beforehand.

_Its use thus is discouraged._ Use of `eval()` requires courage. :heavy_check_mark:

_carefully verified that there is no other option_ Clearly there are ways to cache variants without serializing callbacks for `eval()`. You hint at it above: use php files. This was rejected for batcache because a solution was not found that performed well with WordPress.com's unique deployment.

_paid special attention not to pass any user provided data without properly validating it_ We're just the messenger; it's really up to the people writing the variant determiners. That is very specialized work using a function that has no precedent in related experience, so they are forced to look at code and/or documentation to learn it. This has worked so far on WordPress.com with many different developers writing dozens of variants.

## Caution

Here's what I would do. Make sure nobody can learn about `wp_output_cache_vary()` without seeing a warning about `eval()`. In fact, let me imply a suggestion by showing how I wish I had named it in batcache:

`vary_cache_on_eval()`

The `eval()` at the end would have raised the anti-eval hackles in a beneficial way, urging devs to use caution and avoid mistakes.

Thank you for your patience. This comment ran a bit long because that's how much I love you. I hope somebody is still interested in developing alternative solutions. I'd be happy to see better stuff backported into batcache when you get there. ;-)

**Comment by JJJ** [comment]
> Thank you for your patience.

Thank you! I'm glad that you're chiming in.

> I love you.

I love you back. <3

> I hope somebody is still interested in developing alternative solutions. I'd be happy to see better stuff backported into batcache when you get there. ;-)

I have every good intention of sending pull requests when/if something becomes viable.

> Here's what I would do.

I like that idea, and I think it's still early enough in Spider-Cache's life to rename stuff like this without making anyone too mad.

I lean your way when it comes to `eval()` more than being fully against using it. My comment about it being terrible probably reads differently than the tone with which it was typed, which included a medium eye-roll and a half-sigh, because as you mention it's simply taboo.

**Comment by nathanielks** [comment]
Some more input fwiw: `eval` and `create_function` are only as unsafe as the inputs being sent. Control the inputs, control the result. This happens all the time in Ruby and other dynamic languages and isn't frowned upon at all (except perhaps for the magic-ness of it). `eval()` has been discouraged in the PHP community because _people_ used it terribly, not because it itself is terrible.

If `create_function` does the job, great. If anonymous functions do it better, do that.

All that aside, really excited to see this plugin in the wild and to see a very healthy discussion on GH. :clap: :+1:

**Comment by nathanielks** [comment]
Also in favor of only supporting versions of PHP that are still supported. I.E. drop support for < 5.5. If we're talking about keeping things secure, let's not use versions of PHP that are EOL'd.

**Comment by JJJ** [comment]
Anonymous functions won't work here without using `eval()` directly, but `create_function()` is basically deprecated in PHP7.2, so we'll quickly need alternatives.

For 6.0.0, I've opted to allow for custom callbacks instead, using `is_callable()` in both `wp_output_cache_vary()` and `WP_Spider_Cache_Output::do_variants()`. I'm not convinced it's the *best* option, but it seems fine enough.

Now that `plugin.php` is loaded before `advanced-cache.php`, we could also just throw a filter on the variants too.

I'm comfortable closing this issue now, but please reopen if y'all believe a different/better conclusion can be made here. <3
