### ISSUE TITLE
Oficial wp package

### ISSUE THREAD

**Issue by theuruguayan** [stuttter/wp-spider-cache#17]
Guys, seems that the oficial wp package is missing a file.

Reference https://wordpress.org/support/topic/wp-spider-cacheincludesbase-objectphp-missing-in-220 in there website.

Confirmed that is missing a file from my side too.

**Comment by kevinquinnyo** [comment]
Any update on this?  Plugin is essentially broken right now like this.  I'm asking because I'm actually using this plugin as an option as part of automated wordpress deployments in a platform, and I had to workaround this by having my automation git clone the plugin instead of my normal procedure.

Can this be fixed downstream in the wordpress plugin repository?

**Comment by JJJ** [comment]
Working on it. Sorry, y'all.

**Comment by JJJ** [comment]
This was fixed in 2.2.1, and is fixed in all versions going forward.

Sorry about that. Ugh.

**Comment by kevinquinnyo** [comment]
:+1:
