### ISSUE TITLE
Composit plugin

### ISSUE THREAD

**Issue by szepeviktor** [stuttter/wp-spider-cache#21]
What is the goal of mixing object cache and page cache functionality in wp-spider-cache?

Wouldn't it be more flexible to have a separate, lean page cache plugin?

**Comment by JJJ** [comment]
Good question. IMO, this plugin is pretty lean, considering...

I went with what I felt was a balance of convenience, extensibility, and flexibility. That meant a caching solution that:

* Cached as much as possible
* Cached using the available engine/environment (memcache only for now, because it's all I use)
* Had hooks to allow some customization
* Provided an admin-area UI to help suss out any problems (of which there were actually dozens, many of which in WordPress core)

That said, you can choose which drop-in to use, and not actually drop them both in, and this plugin won't complain. At least, it shouldn't, and it didn't originally. If it does, it shouldn't.

**Comment by szepeviktor** [comment]
Thank you!

> If it does, it shouldn't.

😄
