### ISSUE TITLE
Multisite Difference

### ISSUE THREAD

**Issue by bueltge** [stuttter/wp-spider-cache#7]
Currently add the plugin in each site of a Multisite network a menu item. I think this is not helpful and a overhead for the admin-users of each site. I think the plugin should add on MU activation the menu item in the Network admin area. The table of the cached objects list all site IDs, in each site, not clear for each admin, much more interesting for the Super Admin-User.

Maybe you see this also, I will create a pull request with a solution?

**Comment by JJJ** [comment]
Sure!

On multisite, the top level menu should only be visible and available to super admins, thanks to an unmapped capability check. If regular admins can see it, that's a bug.

**Comment by JJJ** [comment]
After reviewing these changes, I've made some tweaks to make it perform as follows:
- On single-site, Administrators get the mapped `manage_cache` capability, and they can see the UI
- On multi-site, only Super Administrators can see the UI.
- On multi-site, the "Spider Cache" top-level menu item is made available on both blog and network menus.
- On blog menus, only cached data for that blog is visible. This makes it easy to target cached data that is blog specific.
- On network menus, only global data is visible. (Remember that WordPress does _not_ have separate cache groups for any specific network ID.) This makes it easy to target site, network, and user caches.

I think this is the best approach, because it circumvents the insanity of seeing all cached data for all sites in any 1 place, and it removes global cache data from the per-site view.

I'm comfortable closing this issue, now that there is an improved UI. Please reopen if you disagree, or create new issues for any further, more specific issues.

Thanks @bueltge and anyone else following along!
